### ISSUE TITLE
Missing LICENSE declaration

### ISSUE THREAD

**Issue by vicamo** [intel/vision-drivers#9]
Need [LICENSE](https://github.com/intel/vision-drivers/blob/af603b3c182b542cbcb6dda57ec9a7b717ef5a4e/CONTRIBUTING.md?plain=1#L5) info before being able to redistribute/package this driver.

**Comment by tmsundar123** [comment]
New license file is added.

**Comment by tmsundar123** [comment]
Here is the PR https://github.com/intel/vision-drivers/pull/12
